FROM python:3.13

ARG ENVIRONMENT

ENV ENVIRONMENT=${ENVIRONMENT} \
    PYTHONFAULTHANDLER=1 \
    PYTHONUNBUFFERED=1 \
    PYTHONHASHSEED=random \
    PIP_NO_CACHE_DIR=off \
    PIP_DISABLE_PIP_VERSION_CHECK=on \
    PIP_DEFAULT_TIMEOUT=100 \
    POETRY_VERSION=2.1.1 \
    PYTHONPATH=/opt/blog/backend

RUN apt update && \
    apt install -y libpq-dev gcc g++ curl && \
    pip install -U pip setuptools && \
    pip install "poetry==${POETRY_VERSION}"

WORKDIR /opt/blog/backend

COPY backend/requirements.txt /opt/blog/backend/

RUN pip install -r requirements.txt

COPY backend/poetry.lock backend/pyproject.toml /opt/blog/backend/
COPY deployments/entrypoints/fapi-init.sh /usr/local/bin/fapi-init.sh

RUN poetry config virtualenvs.create false

COPY backend /opt/blog/backend

EXPOSE 8000

ENTRYPOINT [ "fapi-init.sh" ]
