FROM node:24-slim as deps

ARG ENVIRONMENT

ENV ENVIRONMENT=${ENVIRONMENT}

RUN mkdir -p /opt/blog/frontend &&\
    chown -R node: /opt/blog/frontend

WORKDIR /opt/blog/frontend

COPY frontend/package.json frontend/yarn.lock /opt/blog/frontend/

RUN yarn install

FROM node:24-slim AS builder

WORKDIR /opt/blog/frontend

COPY frontend /opt/blog/frontend

COPY --from=deps /opt/blog/frontend/node_modules ./node_modules

# Skipping build in dev Dockerfile to avoid backend ENOTFOUND during SSG
# RUN yarn build

EXPOSE 3000

ENTRYPOINT ["yarn", "dev"]
