repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files

- repo: https://github.com/pycqa/isort
  rev: 5.13.2
  hooks:
    - id: isort
      files: ^backend/
      args: [-v, --profile, black, --filter-files, backend/]
      exclude: deployments, tests, frontend

- repo: https://github.com/psf/black
  rev: 24.10.0
  hooks:
    - id: black
      language_version: python3.13
      exclude: deployments, tests, frontend

- repo: https://github.com/pycqa/flake8
  rev: 7.1.1
  hooks:
    - id: flake8
      args: [--config=backend/.flake8, backend]
      exclude: deployments, tests, frontend
