"""empty message

Revision ID: 66f31b29b0c4
Revises: 832eecb5dfb8
Create Date: 2021-02-17 11:46:51.808103

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "66f31b29b0c4"
down_revision = "832eecb5dfb8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("posts", sa.Column("published", sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column("posts", sa.Column("slug", sa.String(), nullable=True))
    op.create_index(op.f("ix_posts_slug"), "posts", ["slug"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_posts_slug"), table_name="posts")
    op.drop_column("posts", "slug")
    op.drop_column("posts", "published")
    # ### end Alembic commands ###
