"""empty message

Revision ID: cece9931e52a
Revises: 66f31b29b0c4
Create Date: 2021-02-21 14:41:21.995805

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "cece9931e52a"
down_revision = "66f31b29b0c4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=True),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("profile", sa.Text(), nullable=False),
        sa.Column("disabled", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.add_column("posts", sa.Column("author_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "posts", "users", ["author_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "posts", type_="foreignkey")
    op.drop_column("posts", "author_id")
    op.drop_table("users")
    # ### end Alembic commands ###
