"""empty message

Revision ID: 157596be3a53
Revises: cece9931e52a
Create Date: 2021-02-24 17:03:08.377903

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "157596be3a53"
down_revision = "cece9931e52a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("hashed_password", sa.String(), nullable=False)
    )
    op.drop_column("users", "password")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "password", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("users", "hashed_password")
    # ### end Alembic commands ###
