name: Tests

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - python-version: "3.13"
    steps:
      - uses: actions/checkout@v6

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v7
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        working-directory: ./backend
        run: |
          pip install -U poetry

      - name: Cache Poetry virtualenv
        uses: actions/cache@v5
        id: cache
        with:
          path: ~/.virtualenvs
          key: poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            poetry-${{ hashFiles('**/poetry.lock') }}

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.7/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Install dependencies
        working-directory: ./backend
        run: |
          poetry install --no-interaction --no-ansi --no-root

      - name: Run tests
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          ORIGINS: ${{ secrets.ORIGIN }}
          TEST_SQLALCHEMY_DATABASE_URI: ${{ secrets.TEST_SQLALCHEMY_DATABASE_URI }}
        run: |
          make test-app
